name: CI

on: [push]

jobs: 
  sast_scan: 
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan: 
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          node-version: 16
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build the image
      run: docker build -f Dockerfile -t myapp:latest .

    #- name: Scan the Docker Image - Docker Scout
    #  run: |
    #    curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
    #    echo ${{secrets.REPO_PWD}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
    #    docker scout quickview 
    #    docker scout cves
    - name: Docker Scout Scan
      uses: docker/scout-action@v1.2.2
      with:
         dockerhub-user: ${{secrets.REPO_USER}}
         dockerhub-password: ${{secrets.REPO_PWD}}
         command: quickview,cves
         only-severities: critical,high
         sarif-file: scout-report.sarif
         
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
         
